# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luish/Schoolz/SD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luish/Schoolz/SD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luish/Schoolz/SD/CMakeFiles /home/luish/Schoolz/SD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luish/Schoolz/SD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openni2_snapper

# Build rule for target.
openni2_snapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni2_snapper
.PHONY : openni2_snapper

# fast build rule for target.
openni2_snapper/fast:
	$(MAKE) -f CMakeFiles/openni2_snapper.dir/build.make CMakeFiles/openni2_snapper.dir/build
.PHONY : openni2_snapper/fast

#=============================================================================
# Target rules for targets named load_pcd

# Build rule for target.
load_pcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load_pcd
.PHONY : load_pcd

# fast build rule for target.
load_pcd/fast:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/build
.PHONY : load_pcd/fast

CloudVisualizer.o: CloudVisualizer.cpp.o

.PHONY : CloudVisualizer.o

# target to build an object file
CloudVisualizer.cpp.o:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/CloudVisualizer.cpp.o
.PHONY : CloudVisualizer.cpp.o

CloudVisualizer.i: CloudVisualizer.cpp.i

.PHONY : CloudVisualizer.i

# target to preprocess a source file
CloudVisualizer.cpp.i:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/CloudVisualizer.cpp.i
.PHONY : CloudVisualizer.cpp.i

CloudVisualizer.s: CloudVisualizer.cpp.s

.PHONY : CloudVisualizer.s

# target to generate assembly for a file
CloudVisualizer.cpp.s:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/CloudVisualizer.cpp.s
.PHONY : CloudVisualizer.cpp.s

load_pcd.o: load_pcd.cpp.o

.PHONY : load_pcd.o

# target to build an object file
load_pcd.cpp.o:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/load_pcd.cpp.o
.PHONY : load_pcd.cpp.o

load_pcd.i: load_pcd.cpp.i

.PHONY : load_pcd.i

# target to preprocess a source file
load_pcd.cpp.i:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/load_pcd.cpp.i
.PHONY : load_pcd.cpp.i

load_pcd.s: load_pcd.cpp.s

.PHONY : load_pcd.s

# target to generate assembly for a file
load_pcd.cpp.s:
	$(MAKE) -f CMakeFiles/load_pcd.dir/build.make CMakeFiles/load_pcd.dir/load_pcd.cpp.s
.PHONY : load_pcd.cpp.s

openni2_snapper.o: openni2_snapper.cpp.o

.PHONY : openni2_snapper.o

# target to build an object file
openni2_snapper.cpp.o:
	$(MAKE) -f CMakeFiles/openni2_snapper.dir/build.make CMakeFiles/openni2_snapper.dir/openni2_snapper.cpp.o
.PHONY : openni2_snapper.cpp.o

openni2_snapper.i: openni2_snapper.cpp.i

.PHONY : openni2_snapper.i

# target to preprocess a source file
openni2_snapper.cpp.i:
	$(MAKE) -f CMakeFiles/openni2_snapper.dir/build.make CMakeFiles/openni2_snapper.dir/openni2_snapper.cpp.i
.PHONY : openni2_snapper.cpp.i

openni2_snapper.s: openni2_snapper.cpp.s

.PHONY : openni2_snapper.s

# target to generate assembly for a file
openni2_snapper.cpp.s:
	$(MAKE) -f CMakeFiles/openni2_snapper.dir/build.make CMakeFiles/openni2_snapper.dir/openni2_snapper.cpp.s
.PHONY : openni2_snapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... openni2_snapper"
	@echo "... load_pcd"
	@echo "... CloudVisualizer.o"
	@echo "... CloudVisualizer.i"
	@echo "... CloudVisualizer.s"
	@echo "... load_pcd.o"
	@echo "... load_pcd.i"
	@echo "... load_pcd.s"
	@echo "... openni2_snapper.o"
	@echo "... openni2_snapper.i"
	@echo "... openni2_snapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

